scheme: Pisces
menu:
  Home: / || fas fa-blog
  Resume: /resume || fas fa-file-alt
  Conferences: /conference || fas fa-users
  Publications: /pub || fas fa-book
menu_settings:
  icons: true
  badges: true
avatar:
  url: /images/avatar.jpg
  rounded: true
